---
- name: restart wireguard
  service:
    name: wg-quick@wg0
    state: restarted

- name: enable wireguard
  service:
    name: wg-quick@wg0
    enabled: yes

- name: disable wireguard
  service:
    name: wg-quick@wg0
    enabled: no
