---
- name: patch status validator
  lineinfile:
    path: "{{ mastodon_home }}/{{mastodon_path}}/app/validators/status_length_validator.rb"
    regexp: 'MAX_CHARS = '
    line: '  MAX_CHARS = (ENV["MAX_CHARS"] || 500).to_i'

- name: patch compose form 1/3
  lineinfile:
    path: "{{ mastodon_home }}/{{mastodon_path}}/app/javascript/mastodon/features/compose/components/compose_form.js"
    regexp: if \(isSubmitting \|\| isUploading \|\| isChangingUpload \|\| length\(fulltext\) > 500 \|\| \(fulltext.length !== 0 && fulltext.trim\(\).length === 0 && !anyMedia\)\) {
    line: "    if (isSubmitting || isUploading || isChangingUpload || length(fulltext) > {{ mastodon_character_limit }} || (fulltext.length !== 0 && fulltext.trim().length === 0 && !anyMedia)) {"

- name: patch compose form 2/3
  lineinfile:
    path: "{{ mastodon_home }}/{{mastodon_path}}/app/javascript/mastodon/features/compose/components/compose_form.js"
    regexp: const disabledButton = disabled \|\| this.props.isUploading \|\| this.props.isChangingUpload \|\| length\(text\) > 500 \|\| \(text.length !== 0 && text.trim\(\).length === 0 && !anyMedia\);
    line: "    const disabledButton = disabled || this.props.isUploading || this.props.isChangingUpload || length(text) > {{ mastodon_character_limit }} || (text.length !== 0 && text.trim().length === 0 && !anyMedia);"

- name: patch compose form 3/3
  lineinfile:
    path: "{{ mastodon_home }}/{{mastodon_path}}/app/javascript/mastodon/features/compose/components/compose_form.js"
    regexp: <div className='character-counter__wrapper'><CharacterCounter max=\{500\} text={text} \/><\/div>
    line: "         <div className='character-counter__wrapper'><CharacterCounter max={{ '{' }}{{ mastodon_character_limit }}{{ '}' }} text={text} /></div>"
