---
- name: Install restic utility
  apt:
    name: restic
    state: present

- name: Copy key for restic
  copy:
    content: "{{ backup_restic_key }}"
    dest: "/root/restic-key"

- name: Create file containing paths to backup
  template:
    src: backup_paths.j2
    dest: "{{ mastodon_home }}/backup_paths"
    mode: '0600'

- name: Copy backupscript
  template:
    src: backup.sh.j2
    dest: "{{mastodon_home}}/backup.sh"
    mode: '0755'

- name: Set Cronjob
  cron:
    name: "backup"
    minute: "0"
    hour: "3"
    job: "{{mastodon_home}}/backup.sh > {{mastodon_home}}/backup.log 2>&1"
