---
- name: Clone mastodon
  git:
    repo: "https://github.com/tootsuite/mastodon.git"
    dest: "{{ mastodon_home }}/{{mastodon_path}}"
    clone: true
    force: yes

- name: Update to latest version
  shell: "git fetch; git checkout $(git tag -l | grep -v 'rc[0-9]*$' | sort -V | tail -n 1)"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Bundle install
  shell: "~/.rbenv/shims/bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without development test"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Yarn install
  command: yarn install --pure-lockfile
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Install systemd sidekiq Service Files
  template:
    src: systemd/mastodon-sidekiq.service.j2
    dest: /etc/systemd/system/mastodon-sidekiq.service
  become: true
  become_user: root

- name: Install systemd web Service Files
  template:
    src: systemd/mastodon-web.service.j2
    dest: /etc/systemd/system/mastodon-web.service
  become: true
  become_user: root

- name: Install systemd streaming Service Files
  template:
    src: systemd/mastodon-streaming.service.j2
    dest: /etc/systemd/system/mastodon-streaming.service
  become: true
  become_user: root

- name: Media cleanup cronjob
  cron:
    name: "media cleanup"
    minute: "15"
    hour: "1"
    job: '/bin/bash -c ''export PATH="$HOME/.rbenv/bin:$PATH"; eval "$(rbenv init -)"; cd {{ mastodon_home }}/{{ mastodon_path }} && RAILS_ENV=production ./bin/tootctl media remove'''

- name: Install mastodon config
  template:
    src: mastodon/.env.production.j2
    dest: "{{ mastodon_home }}/{{ mastodon_path }}/.env.production"

- include: character_limit.yml

- name: Migrate database
  shell: "RAILS_ENV=production ~/.rbenv/shims/bundle exec rails db:migrate"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Precompile assets
  shell: "RAILS_ENV=production ~/.rbenv/shims/bundle exec rails assets:precompile"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Create elasticsearch index
  shell: "RAILS_ENV=production ~/.rbenv/shims/bundle exec rake chewy:upgrade"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Enable and restart mastodon-web
  systemd:
    name: mastodon-web.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: true
  become_user: root

- name: Enable and restart mastodon-streaming
  systemd:
    name: mastodon-streaming.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: true
  become_user: root

- name: Enable and restart mastodon-sidekiq
  systemd:
    name: mastodon-sidekiq.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: true
  become_user: root


- name: import old statuses to elasticsearch
  shell: "RAILS_ENV=production ~/.rbenv/shims/bundle exec rake chewy:sync"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"
