---
- name: download rickroll.mp4
  get_url:
    url: https://shortlink.l12c.eu/rickroll.mp4
    dest: /home/mastodon/live/public/rickroll.mp4
  when:
    - rickroll_url is defined

- name: Copy nginx config
  template:
    src: nginx/mastodon.conf.j2
    dest: /etc/nginx/sites-available/mastodon.conf
  when:
    - mastodon_host is defined

- name: Symlink enabled site
  file:
    src: "/etc/nginx/sites-available/mastodon.conf"
    dest: "/etc/nginx/sites-enabled/mastodon.conf"
    state: link
  when:
    - mastodon_host is defined
  notify:
  - reload nginx
