---
- name: download rickroll.mp4
  copy:
    src: nginx/rickroll.mp4
    dest: "{{ mastodon_path }}/public/rickroll.mp4"
  when:
    - rickroll_urls is defined

- name: Copy nginx config
  template:
    src: nginx/mastodon.conf.j2
    dest: /etc/nginx/sites-available/mastodon.conf
  when:
    - mastodon_host is defined

- name: Symlink enabled site
  file:
    src: "/etc/nginx/sites-available/mastodon.conf"
    dest: "/etc/nginx/sites-enabled/mastodon.conf"
    state: link
  when:
    - mastodon_host is defined
  notify:
  - reload nginx
