---
- name: Install packages # TODO: Make more effective!
  package:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
    state: latest
    install_recommends: no

- name: nodejs alternative
  alternatives:
    name: node
    link: /usr/bin/node
    path: /usr/bin/nodejs
