---
  - import_tasks: packages.yml
  - include: sudo.yml
  - include: molly-guard.yml

  - include: user.yml user={{ users }}
    tags: user
    
  - name: adding message of the day
    template: dest=/etc/motd
              src=motd
              owner=root group=root mode=0644
