---
- name: Bootstrapping
  hosts: all
  roles:
    - init
    - jnv.unattended-upgrades
    - base
  tags:
    - base
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - postgres
  tags:
    - postgres

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - redis
  tags:
    - redis

- hosts: all
  roles:
    - geerlingguy.java
    - geerlingguy.elasticsearch
  tags:
    - elasticsearch

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - mastodon
  tags:
    - mastodon
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - backup
  tags:
    - backup
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - wireguard
  tags:
    - wireguard
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - nodeexporter
  tags:
    - nodeexporter
  become: true
