---
- name: Bootstrapping
  hosts: all
  roles:
    - init
    - jnv.unattended-upgrades
    - base
  tags:
    - base
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - postgres
  tags:
    - postgres

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - redis
  tags:
    - redis

- hosts: all
  roles:
    - elasticsearch
  vars:
    update_java: true
    es_java_install: true
    es_version: 7.17.2
    es_allow_downgrades: true
    es_data_dirs:
      - "/var/elasticsearch/data"
    es_log_dir: "/var/log/elasticsearch/"
    es_config:
      node.name: "node1"
      cluster.name: "cutes-cluster"
      node.master: true
    es_heap_size: 1g
  tags:
    - elasticsearch

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - mastodon
  tags:
    - mastodon
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - backup
  tags:
    - backup
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - wireguard
  tags:
    - wireguard
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - nodeexporter
  tags:
    - nodeexporter
  become: true
