---
- name: Bootstrapping
  hosts: all
  roles:
    - init
    - jnv.unattended-upgrades
    - base
  tags:
    - base
  become: true

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - postgres
  tags:
    - postgres

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - redis
  tags:
    - redis

- hosts: all
  roles:
    - elasticsearch
  vars:
    update_java: true
    es_java_install: true
    es_version: 6.8.7
    es_allow_downgrades: true
    es_data_dirs:
      - "/var/elasticsearch/data"
    es_log_dir: "/var/log/elasticsearch/"
    es_config:
      node.name: "node1"
      cluster.name: "cutes-cluster"
      #discovery.seed_hosts: "localhost:9301"
      #http.port: "{{ mastodon_es_port }}"
      #transport.port: 9301
      node.master: true
      #bootstrap.memory_lock: true
    es_heap_size: 1g
    #es_api_port: "{{ mastodon_es_port }}"
  tags:
    - elasticsearch

- hosts: all
  vars_files:
    - "../vars/{{ ansible_os_family|lower }}_vars.yml"
  roles:
    - mastodon
  tags:
    - mastodon
  become: true

- hosts: all
vars_files:
  - "../vars/{{ ansible_os_family|lower }}_vars.yml"
roles:
  - backup
tags:
  - backup
become: true
