---
- name: uninstall wireguard (Ubuntu)
  when: ansible_distribution == 'Ubuntu'
  apt:
    pkg:
      - linux-headers-generic
      - wireguard-tools
      - wireguard-dkms
    state: absent

- name: delete configuration file
  file:
    dest: /etc/wireguard/wg0.conf
    state: absent

- name: remove allow traffic though wireguard in firewall
  ufw:
    rule: allow
    from_ip: '192.168.123.1'
    delete: yes
